spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/growing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
  redis:
    database: 0
    timeout: 10000
    host: 127.0.0.1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
jwt:
  secret: SMb15jyu1UuaPRC3PqFr4DPoHifZPhhkBNlEsJttMMWFH7hxBL+OhVcu0DEDwCgNth+O/NYLErLxQHZPA6ZKSA==
  expiration: 604800000  # 过期时间，单位为毫秒，这里设置为 7*24 小时
erupt-app:
  # 是否开启水印，1.12.0 及以上版本支持
  water-mark: false
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verify-code-count: 2
  # 登录密码是否加密传输，特殊场景如：LDAP登录可关闭该功能获取密码明文
  pwd-transfer-encrypt: true
  # 是否开启密码重置功能，关闭后前端会屏蔽所有重置密码的入口适用于 ldap 等场景，1.12.7 及以上版本支持
  reset-pwd: true
  # 多语言配置
  locales: [ # 语言包编码参考：https://www.yuque.com/erupts/erupt/gg3c93#TTkZY
    "zh-CN",      # 简体中文
    "en-US",      # English
  ]
  # 自定义登录页路径，1.10.6 及以上版本支持，支持http网络路径
  #login-page-path: /customer-login.html
erupt:
  # 是否开启csrf防御
  csrf-inspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redis-session: false
  # redis session是否自动续期，1.10.8及以上版本支持
  redis-session-refresh: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  upload-path: /Users/liuxiaonan/Downloads/erupt/pictures
  # 是否保留上传文件原始名称
  keep-upload-file-name: false
  # 项目初始化方式，NONE 不执行初始化代码、EVERY 每次启动都进行初始化、FILE 通过标识文件判断是否需要初始化
  init-method-enum: file
  # 默认语言，1.12.3 及以上版本支持
  default-locales: zh-CN
  # 是否开启任务调度（导入erupt-job时有效）
  job.enable: true
  # 是否开启日志采集，开启后可在系统日志中查看实时日志 1.12.14 及以上版本支持
  log-track: true
  # 日志采集最大暂存行数 1.12.14 及以上版本支持
  log-track-cache-size: 1000
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security:
    record-operate-log: true
  upms:
    # 登录 session 时长
    # 1.12.18以下版本 且 redis-session 为 false 时控制有效期的方法：server.servlet.session.timeout
    expire-time-by-login: 60
    # 严格的角色菜单策略，如果非管理员用户拥有“角色管理权限”则仅能编辑已有权限的角色菜单
    strict-role-menu-legal: true
    # 系统初始化时默认超管用户名 1.12.18及以上版本支持
    default-account: unitx
    # 系统初始化时默认超管密码 1.12.18及以上版本支持
    default-password: '!@#$'
magic-api:
  #配置web页面入口
  web: /magic/web
  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: /Users/liuxiaonan/Downloads/erupt/data/magic-api
  response-code:
    success: 200
    error: 60000
    invalid: 40000
    exception: 50000
  page:
    size: size # 页大小的请求参数名称 缺省时为size
    page: page # 页码的请求参数名称 缺省时为page
    default-page: 1 # 自定义默认首页 缺省时为1
    default-size: 10 # 自定义为默认页大小 缺省时为10