package com.ig.game_admin.entity;

/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:27:31

    t_event_config(活动配置表)
    ---------------------------------------------------
    id                                 PKInteger    //<<自增长>>
    event_id(活动ID)                   String(64)   //<<唯一索引,非空>>
    event_name(活动名称)               String(100)  //<<非空>>
    event_type(类型)                   Enum         //类型，1-登录奖励，2-任务活动，3-限时挑战
    start_time(开始时间)               Date
    end_time(结束时间)                 Date
    display_priority(显示优先级)       Integer
    icon_url(图标url)                  String(255)
    description(描述)                  String(99999)
    rule_config(规则配置)              json         //<<类名:json>>
    reward_config(奖励配置)            json         //<<类名:json>>
    is_active(是否激活)                Enum         //<<缺省值:1>>
    created_at(创建时间)               Date
    updated_at(更新时间)               Date
 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.EditType;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.ChoiceType;
import xyz.erupt.annotation.sub_field.sub_edit.DateType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.annotation.sub_field.sub_edit.VL;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;
import java.util.Date;

@Erupt(
        name = "活动配置表"
)
@Table(name = "t_event_config")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TEventConfigEntity extends HyperModel {

    @Column(length = 64, nullable = false, unique = true)
    @EruptField(
            views = @View(
                    title = "活动ID",
                    width = "120"
            ),
            edit = @Edit(
                    title = "活动ID",
                    show = false,
                    search = @Search
            )
    )
    private String eventId;

    @Column(length = 100, nullable = false)
    @EruptField(
            views = @View(
                    title = "活动名称",
                    width = "120"
            ),
            edit = @Edit(
                    title = "活动名称",
                    notNull = true,
                    search = @Search
            )
    )
    private String eventName;

    @EruptField(
            views = @View(
                    title = "类型",
                    desc = "类型，1-登录奖励，2-任务活动，3-限时挑战",
                    width = "120"
            ),
            edit = @Edit(
                    title = "类型",
                    desc = "类型，1-登录奖励，2-任务活动，3-限时挑战",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "4", label = "4"),
                            @VL(value = "0", label = "0"),
                            @VL(value = "3", label = "3"),
                            @VL(value = "2", label = "2")
                    }),
                    search = @Search
            )
    )
    private Integer eventType;

    @EruptField(
            views = @View(
                    title = "开始时间",
                    width = "120"
            ),
            edit = @Edit(
                    title = "开始时间",
                    type = EditType.DATE,
                    dateType = @DateType(type = DateType.Type.DATE),
                    search = @Search
            )
    )
    private Date startTime;

    @EruptField(
            views = @View(
                    title = "结束时间",
                    width = "120"
            ),
            edit = @Edit(
                    title = "结束时间",
                    type = EditType.DATE,
                    dateType = @DateType(type = DateType.Type.DATE)
            )
    )
    private Date endTime;

    @EruptField(
            views = @View(
                    title = "显示优先级",
                    width = "120"
            ),
            edit = @Edit(
                    title = "显示优先级"
            )
    )
    private Integer displayPriority;

    @Column(length = 255)
    @EruptField(
            views = @View(
                    title = "图标url",
                    width = "120"
            ),
            edit = @Edit(
                    title = "图标url"
            )
    )
    private String iconUrl;

    @Lob
    @EruptField(
            views = @View(
                    title = "描述",
                    width = "120"
            ),
            edit = @Edit(
                    title = "描述"
            )
    )
    private String description;

    @EruptField(
            views = @View(
                    title = "是否激活",
                    width = "120"
            ),
            edit = @Edit(
                    title = "是否激活",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "3", label = "3"),
                            @VL(value = "2", label = "2"),
                            @VL(value = "1", label = "1")
                    })
            )
    )
    private Integer isActive;
}
