package com.ig.game_admin.entity;

/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:44:55

    t_friend_relations(好友关系表)
    ------------------------------------------
    id                         PKInteger    //<<自增长>>
    user_no(用户编号)          String(64)   //<<非空>>
    friend_no(好友编号)        String(50)   //<<非空>>
    relation_status(状态)      Enum         //<<缺省值:0>>状态，0-申请中，1-好友，2-黑名单
    create_time(创建时间)      Date
    update_time(更新时间)      Date
    create_user(创建人)        String(64)
    update_user(更新人)        String(64)


 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.EditType;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.ChoiceType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.annotation.sub_field.sub_edit.VL;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;



@Erupt(
        name = "好友关系表"
)
@Table(name = "t_friend_relations")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TFriendRelationsEntity extends HyperModel{
    @Column(length = 64, nullable = false)
    @EruptField(
            views = @View(
                    title = "用户编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "用户编号",
                    show = false,
                    search = @Search
            )
    )
    private String userNo;

    @Column(length = 50, nullable = false)
    @EruptField(
            views = @View(
                    title = "好友编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "好友编号",
                    show = false,
                    search = @Search
            )
    )
    private String friendNo;

    @EruptField(
            views = @View(
                    title = "状态",
                    desc = "状态，0-申请中，1-好友，2-黑名单",
                    width = "120"
            ),
            edit = @Edit(
                    title = "状态",
                    desc = "状态，0-申请中，1-好友，2-黑名单",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "1", label = "好友"),
                            @VL(value = "2", label = "黑名单"),
                            @VL(value = "0", label = "申请中")
                    }),
                    search = @Search
            )
    )
    private Integer relationStatus;
}

