package com.ig.game_admin.entity;

/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:47:16

t_front_user(用户账户信息表)
----------------------------------------------------------
id                                         PKInteger    //<<自增长>>
account(账号)                              String(50)   //<<唯一索引,非空>>
nick_name(昵称)                            String(50)
avatar(头像url)                            String(255)
password(密码)                             String(255)  //<<非空>>
email(邮箱)                                String(100)
phone(手机号)                              String(20)
gender(性别)                               Enum         //<<缺省值:0>>性别，0-女，1-男
status(状态)                               Enum         //<<缺省值:1>>状态，0-禁用，1-启用
last_login_time(最近一次登录时间)          Date
user_no(用户编号)                          String(50)   //<<唯一索引,非空>>
platform(平台)                             Enum         //<<类名:enum>>
device_id(设备ID)                          String(50)
login_ip(登录ip)                           String(50)
create_time(创建时间)                      Date
update_time(更新时间)                      Date
create_user(创建人)                        String(64)
update_user(更新人)                        String(64)


 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.EditType;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.ChoiceType;
import xyz.erupt.annotation.sub_field.sub_edit.DateType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.annotation.sub_field.sub_edit.VL;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;

@Erupt(
        name = "用户账户信息表"
)
@Table(name = "t_front_user")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TFrontUserEntity extends HyperModel{

    @Column(length = 50, nullable = false, unique = true)
    @EruptField(
            views = @View(
                    title = "用户编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "用户编号",
                    show = false
            )
    )
    private String userNo;

    @Column(length = 50, nullable = false, unique = true)
    @EruptField(
            views = @View(
                    title = "账号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "账号",
                    notNull = true,
                    search = @Search
            )
    )
    private String account;

    @Column(length = 50)
    @EruptField(
            views = @View(
                    title = "昵称",
                    width = "120"
            ),
            edit = @Edit(
                    title = "昵称",
                    search = @Search
            )
    )
    private String nickName;

    @Column(length = 255)
    @EruptField(
            views = @View(
                    title = "头像url",
                    width = "120"
            ),
            edit = @Edit(
                    title = "头像url",
                    search = @Search
            )
    )
    private String avatar;

    @Column(length = 255, nullable = false)
    @EruptField(
            views = @View(
                    title = "密码",
                    width = "120"
            ),
            edit = @Edit(
                    title = "密码",
                    show = false,
                    search = @Search
            )
    )
    private String password;

    @Column(length = 100)
    @EruptField(
            views = @View(
                    title = "邮箱",
                    width = "120"
            ),
            edit = @Edit(
                    title = "邮箱"
            )
    )
    private String email;

    @Column(length = 20)
    @EruptField(
            views = @View(
                    title = "手机号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "手机号"
            )
    )
    private String phone;

    @EruptField(
            views = @View(
                    title = "性别",
                    desc = "性别，0-女，1-男",
                    width = "120"
            ),
            edit = @Edit(
                    title = "性别",
                    desc = "性别，0-女，1-男",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "0", label = "女"),
                            @VL(value = "1", label = "男"),
                            @VL(value = "2", label = "未知")
                    })
            )
    )
    private Integer gender;

    @EruptField(
            views = @View(
                    title = "状态",
                    desc = "状态，0-禁用，1-启用",
                    width = "120"
            ),
            edit = @Edit(
                    title = "状态",
                    desc = "状态，0-禁用，1-启用",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "0", label = "禁用"),
                            @VL(value = "1", label = "启用")
                    })
            )
    )
    private Integer status;

    @EruptField(
            views = @View(
                    title = "最近一次登录时间",
                    width = "120"
            ),
            edit = @Edit(
                    title = "最近一次登录时间",
                    type = EditType.DATE,
                    show = false,
                    dateType = @DateType(type = DateType.Type.DATE)
            )
    )
    private Date lastLoginTime;



    @EruptField(
            views = @View(
                    title = "平台",
                    width = "120"
            ),
            edit = @Edit(
                    title = "平台",
                    type = EditType.CHOICE,
                    show = false,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "1", label = "android"),
                            @VL(value = "2", label = "ios"),
                            @VL(value = "3", label = "pc"),
                            @VL(value = "4", label = "other")
                    })
            )
    )
    private Integer platform;

    @Column(length = 50)
    @EruptField(
            views = @View(
                    title = "设备ID",
                    width = "120"
            ),
            edit = @Edit(
                    title = "设备ID",show = false
            )
    )
    private String deviceId;

    @Column(length = 50)
    @EruptField(
            views = @View(
                    title = "登录ip",
                    width = "120"
            ),
            edit = @Edit(
                    title = "登录ip",show = false
            )
    )
    private String loginIp;

}

