package com.ig.game_admin.entity;

/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:48:32

t_item_config(道具信息表)
-------------------------------------------------
id                             PKInteger    //<<自增长>>
no(编号)                       String(64)   //<<唯一索引,非空>>
name(名称)                     String(100)  //<<非空>>
pic_url(图片链接)              String(255)
width(宽)                      Integer
height(高)                     Integer
type(类型)                     Enum         //类型，1-消除类，2-增益类，3-装饰类
func(功能说明)                 String(99999)
remark(描述)                   String(99999)
level(级别)                    Integer
can_purchase(是否可购买)       Enum         //<<缺省值:1>>
gem_price(钻石数量)            Integer
create_time(创建时间)          Date
update_time(更新时间)          Date
create_user(创建人)            String(64)
update_user(更新人)            String(64)


 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_erupt.Power;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.EditType;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.ChoiceType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.annotation.sub_field.sub_edit.VL;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;



@Erupt(
        name = "道具信息表"
)
@Table(name = "t_item_config")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TItemConfigEntity extends HyperModel{

    @Column(length = 64, nullable = false, unique = true)
    @EruptField(
            views = @View(
                    title = "编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "编号",
                    show = false,
                    search = @Search
            )
    )
    private String no;

    @Column(length = 100, nullable = false)
    @EruptField(
            views = @View(
                    title = "名称",
                    width = "120"
            ),
            edit = @Edit(
                    title = "名称",
                    notNull = true,
                    search = @Search
            )
    )
    private String name;

    @Column(length = 255)
    @EruptField(
            views = @View(
                    title = "图片链接",
                    width = "120"
            ),
            edit = @Edit(
                    title = "图片链接",
                    search = @Search
            )
    )
    private String picUrl;

    @EruptField(
            views = @View(
                    title = "宽",
                    width = "120"
            ),
            edit = @Edit(
                    title = "宽",
                    search = @Search
            )
    )
    private Integer width;

    @EruptField(
            views = @View(
                    title = "高",
                    width = "120"
            ),
            edit = @Edit(
                    title = "高"
            )
    )
    private Integer height;

    @EruptField(
            views = @View(
                    title = "类型",
                    desc = "类型，1-消除类，2-增益类，3-装饰类",
                    width = "120"
            ),
            edit = @Edit(
                    title = "类型",
                    desc = "类型，1-消除类，2-增益类，3-装饰类",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "1", label = "消除类"),
                            @VL(value = "2", label = "增益类"),
                            @VL(value = "3", label = "装饰类"),
                    })
            )
    )
    private Integer type;

    @Lob
    @EruptField(
            views = @View(
                    title = "功能说明",
                    width = "120"
            ),
            edit = @Edit(
                    title = "功能说明"
            )
    )
    private String func;

    @Lob
    @EruptField(
            views = @View(
                    title = "描述",
                    width = "120"
            ),
            edit = @Edit(
                    title = "描述"
            )
    )
    private String remark;

    @EruptField(
            views = @View(
                    title = "级别",
                    width = "120"
            ),
            edit = @Edit(
                    title = "级别"
            )
    )
    private Integer level;

    @EruptField(
            views = @View(
                    title = "是否可购买",
                    width = "120"
            ),
            edit = @Edit(
                    title = "是否可购买",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "0", label = "否"),
                            @VL(value = "1", label = "是")
                    })
            )
    )
    private Integer canPurchase;

    @EruptField(
            views = @View(
                    title = "钻石数量",
                    width = "120"
            ),
            edit = @Edit(
                    title = "钻石数量"
            )
    )
    private Integer gemPrice;

}

