package com.ig.game_admin.entity;

/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:49:39

t_leader_board(排行榜表)
------------------------------------------
id                         PKInteger    //<<自增长>>
user_no(用户编号)          String(64)   //<<非空>>
score_type(分数类型)       Enum         //分数类型，1-最高分，2-总消除数，3-通关数
score_value(分数值)        Integer
season_id(赛季ID)          Integer
create_time(创建时间)      Date
update_time(更新时间)      Date
create_user(创建人)        String(64)
update_user(更新人)        String(64)


 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_erupt.Power;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.EditType;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.ChoiceType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.annotation.sub_field.sub_edit.VL;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;



@Erupt(
        name = "排行榜表"
)
@Table(name = "t_leader_board")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TLeaderBoardEntity extends HyperModel{


    @Column(length = 64, nullable = false)
    @EruptField(
            views = @View(
                    title = "用户编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "用户编号",
                    show = false,
                    search = @Search
            )
    )
    private String userNo;

    @EruptField(
            views = @View(
                    title = "分数类型",
                    desc = "分数类型，1-最高分，2-总消除数，3-通关数",
                    width = "120"
            ),
            edit = @Edit(
                    title = "分数类型",
                    desc = "分数类型，1-最高分，2-总消除数，3-通关数",
                    type = EditType.CHOICE,
                    choiceType = @ChoiceType(vl = {
                            @VL(value = "1", label = "最高分"),
                            @VL(value = "2", label = "总消除数"),
                            @VL(value = "3", label = "通关数"),
                    }),
                    search = @Search
            )
    )
    private Integer scoreType;

    @EruptField(
            views = @View(
                    title = "分数值",
                    width = "120"
            ),
            edit = @Edit(
                    title = "分数值",
                    search = @Search
            )
    )
    private Integer scoreValue;

    @EruptField(
            views = @View(
                    title = "赛季ID",
                    width = "120"
            ),
            edit = @Edit(
                    title = "赛季ID",
                    search = @Search
            )
    )
    private Integer seasonId;
}

