package com.ig.game_admin.entity;
/*
 * Copyright © 2025 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5-7-25 05:51:36

t_user_game_data(用户游戏数据表)
--------------------------------------------------------------
id                                            PKInteger    //<<自增长>>
user_no(用户编号)                             String(64)   //<<非空>>
level(当前等级)                               Integer      //<<缺省值:1>>
exp(当前体力值)                               Integer      //<<缺省值:0>>
gems(钻石数量)                                Integer      //<<缺省值:0>>
cards(道具卡数量)                             Integer      //<<缺省值:0>>
max_unlocked_stage(已解锁的最大关卡)          Integer      //<<缺省值:1>>
total_play_time(总游戏时长)                   Integer      //<<缺省值:0>>总游戏时长（秒）
create_time(创建时间)                         Date
update_time(更新时间)                         Date
create_user(创建人)                           String(64)
update_user(更新人)                           String(64)


 */

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.sub_erupt.Power;
import xyz.erupt.annotation.sub_field.Edit;
import xyz.erupt.annotation.sub_field.View;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.upms.model.base.HyperModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;



@Erupt(
        name = "用户游戏数据表"
)
@Table(name = "t_user_game_data")   //数据库表名
@Entity
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
public class TUserGameDataEntity extends HyperModel{

    @Column(length = 64, nullable = false)
    @EruptField(
            views = @View(
                    title = "用户编号",
                    width = "120"
            ),
            edit = @Edit(
                    title = "用户编号",
                    show = false,
                    search = @Search
            )
    )
    private String userNo;

    @EruptField(
            views = @View(
                    title = "当前等级",
                    width = "120"
            ),
            edit = @Edit(
                    title = "当前等级",
                    search = @Search
            )
    )
    private Integer level;

    @EruptField(
            views = @View(
                    title = "当前经验值",
                    width = "120"
            ),
            edit = @Edit(
                    title = "当前经验值",
                    search = @Search
            )
    )
    private Integer exp;

    @EruptField(
            views = @View(
                    title = "当前体力值",
                    width = "120"
            ),
            edit = @Edit(
                    title = "当前体力值",
                    search = @Search
            )
    )
    private Integer energy;

    @EruptField(
            views = @View(
                    title = "钻石数量",
                    width = "120"
            ),
            edit = @Edit(
                    title = "钻石数量",
                    search = @Search
            )
    )
    private Integer gems;

    @EruptField(
            views = @View(
                    title = "道具卡数量",
                    width = "120"
            ),
            edit = @Edit(
                    title = "道具卡数量"
            )
    )
    private Integer cards;

    @EruptField(
            views = @View(
                    title = "已解锁的最大关卡",
                    width = "120"
            ),
            edit = @Edit(
                    title = "已解锁的最大关卡"
            )
    )
    private Integer maxUnlockedStage;

    @EruptField(
            views = @View(
                    title = "总游戏时长",
                    desc = "总游戏时长（秒）",
                    width = "120"
            ),
            edit = @Edit(
                    title = "总游戏时长",
                    desc = "总游戏时长（秒）"
            )
    )
    private Integer totalPlayTime;

}

